version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
      - 443:443