version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
      - 443:443
      - 3000:3000

  deno:
    image: denoland/deno:alpine
    container_name: socket_server
    build:
      context: .
    command: deno run -A /usr/share/main.ts
    volumes:
      - ./main.ts:/usr/share/main.ts
    expose:
      - 8080